# BookHelp Configuration

# Sets Book Title
title: "§lHelp!"

# Sets Book Author
author: "Potatoe"

# Set Page Text
# Use '§' For Color
# Use '\n' For New Line

text-1: "§lBookHelp\n\n§r§7Download At https://github.com/PotatoeTrainYT/BookHelp"
text-2: "§lPage 2"
text-3: "§lPage 3"
